### ISSUE TITLE
.disconnect() breaks additional observe calls

### ISSUE THREAD

**Issue by JMStewart** [juggle/resize-observer#104]
**Describe the bug**
When I call `.disconnect()` on an observer, it prevents the observer from being used again. It won't throw any errors, but the resize events will not fire for anything added after calling disconnect.
The native implementation just clears the current list of observe targets, but then you can start observing again with the same instance. So I can use disconnect to clear all current observers, and then add new ones.

**Comment by TremayneChrist** [comment]
Hi @JMStewart,

I seem to have originally overlooked the details of the disconnect API. Unfortunately it's not a super simple fix, so it may take a bit of time testing before I can publish a release. Hopefully I can get it done this week though.
