### ISSUE TITLE
Using this polyfill with polyfill.io

### ISSUE THREAD

**Issue by nicooprat** [juggle/resize-observer#105]
Many thanks for this polyfill that worked a lot better than https://github.com/que-etc/resize-observer-polyfill!

I suggested to use this polyfill in Financial Times' polyfill.io service instead of an old one:

* Is it OK with you?
* [Some tests seem to fail](https://github.com/Financial-Times/polyfill-library/pull/644#issuecomment-632890850), would you mind to take a look?

```
Failures:
 - safari/9.1:
    -> ResizeObserver ResizeObserver Observer should allow trying to unobserve multiple times.
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=ResizeObserver
       done() called multiple times
```

Here's the PR https://github.com/Financial-Times/polyfill-library/pull/644#issuecomment-632890850

Regards.

**Comment by TremayneChrist** [comment]
Hi @nicooprat,

Really appreciate you trying to get this into polyfil.io and I'm glad it's working well for you!

I'll take a look into the tests and see what I can do.

**Comment by TremayneChrist** [comment]
I'll have to fire up an instance of Safari 9.1 to debug this properly. Looking at the code I'm not sure how this is even possible, especially as the other tests for multiple observes appear to be working fine.

**Comment by TremayneChrist** [comment]
@nicooprat the dependencies required for the polyfill have changed recently and therefore they will need to be updated in the PR for polyfill.io.

`Map` → `WeakMap`

Also the tests will have to change slightly as this polyfill didn't follow the spec correctly for the `disconnect` API. You can see the issue here (#104).

https://github.com/juggle/resize-observer/releases/tag/v3.2.0

**Comment by TremayneChrist** [comment]
I cannot seem to reproduce the error in Safari 9.1. I only see the callback being fired once.

```js
var el = document.createElement('div');
var el2 = el.cloneNode();
document.body.appendChild(el);
document.body.appendChild(el2);
var ro = new ResizeObserver(function (entries) {
  console.log('RO', entries.length);
});
ro.observe(el);
ro.observe(el2);
ro.unobserve(el2);
ro.unobserve(el2);

// RO 1
```
