### ISSUE TITLE
The UMD build doesn't not export the globals as expected

### ISSUE THREAD

**Issue by trusktr** [juggle/resize-observer#113]
**Describe the bug**

Loading `https://unpkg.com/@juggle/resize-observer@3.2.0/lib/exports/resize-observer.umd.js` via script tag creates a global `ResizeObserver` variable that is an object containing the `ResizeObserver` constructor.

**To Reproduce**

```html
<script src="https://unpkg.com/@juggle/resize-observer@3.2.0/lib/exports/resize-observer.umd.js"></script>
<script>
  new ResizeObserver(() => {}) // error, see console
</script>
```

live example: https://plnkr.co/edit/pebOym3SOvT0ZABB

**Expected behavior**

It would be great if including it in a script tag put the correct globals in place.

**Comment by trusktr** [comment]
Ah, here's how to do it: https://github.com/rollup/rollup/issues/494#issuecomment-268243574

**Comment by trusktr** [comment]
Made a PR, but haven't tested it yet: https://github.com/juggle/resize-observer/pull/114

**Comment by trusktr** [comment]
Apparently that doesn't work as prescribed. Here's the header it generates:

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (global = global || self, factory(global.window = {}));
}(this, (function (exports) { 'use strict';
```

which means `{}` gets passed in as `exports`, not `window`. Maybe that Rollup comment is for an older version.

**Comment by trusktr** [comment]
Oh wait, it works. Just needed to add the `extends: true` option, so that it extends the passed-in object instead of replacing it. Updated the PR.

Now the header looks like this:

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (global = global || self, factory(global.window = global.window || {}));
}(this, (function (exports) { 'use strict';
```

**Comment by TremayneChrist** [comment]
Included in v4 preview
