### ISSUE TITLE
[Question] - How does this package compares with que-etc/resize-observer-polyfill ?

### ISSUE THREAD

**Issue by TiagoPortfolio** [juggle/resize-observer#121]
Hi all! :wave: 
Thanks for this package and for keeping it updated frequently!

I noticed that this package [resize-observer-polyfill](https://github.com/que-etc/resize-observer-polyfill) is the most popular at the moment but its last release was 2 years ago.

I would like to understand how your package compares with [resize-observer-polyfill](https://github.com/que-etc/resize-observer-polyfill).

Cheers!

**Comment by mdingena** [comment]
For one, the spec has changed since 2018, so if that package has not been updated since then, their claim to follow the spec is inaccurate.

Arguably the most important missing feature from that package is the ability to return `borderBoxSize` and `contentBoxSize` properties. It only supports the (now legacy) `contentRect` property, which you probably shouldn't use.

**Comment by TremayneChrist** [comment]
Hi @TiagoPortfolio - great question and test on my memory 😄 

I tried to use and improve the resize-observer-polyfill myself, before working on this polyfill, and while it's great for the basics, you can quickly run into problems with it. Especially when you start applying more complex css.

If you're observing a standard box, with basic padding and no scroll regions, resize-observer-polyfill will probably be ok for you. If you need to rely on it as an solid backup for the real thing, you might find it will let you down and like @mdingena said, it's way behind on the spec now.

In my experience, it struggled with animation and transitions. Also the delay in reporting changes and the workarounds required for css pseudo states put me off a bit - it just wasn't reliable enough.

This polyfill tries to follow the spec to the letter, notably:
1. What elements should actually fire notifications (Mostly anything but, non-replaced inline elements)
2. When the notification should actually be fired (after layout, before paint)
3. Switches inline/block sizes based on writing mode
4. Supports SVG specification
5. Adds box size options and reports them based on the latest spec (`ResizeObserverSize[]`)
6. Factors in padding, border and scrollbar width (for all sides)
7. Returns correct values when the box size changes (e.g. `box-sizing:border-box`)
8. Provides infinite loop detection and prevention
9. Fires notifications when elements are added/removed from DOM
10. Fires notification when elements display is set to none (and back again)

**Comment by TiagoPortfolio** [comment]
Alright @mdingena and @TremayneChrist , thanks a lot for your feedback!
I just learned that we can create discussions so next time I will create a discussion instead of an issue whenever I have questions like this.

Cheers!
