### ISSUE TITLE
Missing null check

### ISSUE THREAD

**Issue by meetdave3** [juggle/resize-observer#131]
Hi! 

It's been 3 days since i've started using resize-observer on production, and have recently received the following error on Sentry

Referring to: https://github.com/juggle/resize-observer/blob/c92bcde23f23a5bc7b6d6e32449dec1e540c419f/src/utils/queueMicroTask.ts#L4
Error: TypeError Array.forEach(<anonymous>)
Description: Cannot convert undefined or null to object
OS: Windows 10
Browser: Chrome v74.0.3729
@juggle/resize-observer v3.3.1

It seems like a missing null check?
I find it difficult to replicate this issue locally. However, this error has been occurring frequently

I'm using with `react-use-measure` lib, like so:

```ts
import useMeasure from 'react-use-measure'
import { ResizeObserver as Polyfill } from '@juggle/resize-observer'

const polyfill = (typeof window !== 'undefined' && window?.ResizeObserver) || Polyfill
const [ref, { height }] = useMeasure({ polyfill })

```

**Comment by TremayneChrist** [comment]
Hi @meetdave3,

This is an internal util which is always passed the same internal callbacks - no null check should be required here. Can you see if anything is causing this in the `react-use-measure` library? Maybe something in the RO callback which is created from the lib itself?

Do you have a stack trace to look at?

**Comment by TremayneChrist** [comment]
@meetdave3 did you have a chace to look into this a bit more?

**Comment by meetdave3** [comment]
Hi @TremayneChrist, sorry for the late reply. 

Strangely the bug doesn't appear on Sentry any more. Will keep you posted if there's anything more on my side. 

Closing this for now.
Thanks for quick reply, appreciate it
