### ISSUE TITLE
the >>> and /deep/ combinators have been deprecated. Use :deep() instead

### ISSUE THREAD

**Issue by rosell-dk** [juggle/resize-observer#137]
We get "the >>> and /deep/ combinators have been deprecated. Use :deep() instead" warnings in 3.4.0.

The warning says it all...

It is in this file: /lib/ResizeObserverDetail.js

**Comment by TremayneChrist** [comment]
Hi @rosell-dk this library doesn't write or modify any CSS. Are you doing anything to the element inside of the resize notification callback? Something that could affect styles?
