### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by vincent157664** [juggle/resize-observer#140]
I've faced this error:`ResizeObserver loop completed with undelivered notifications` while changing the style of React component using useMediaQuery() function in MUI.

**Comment by waytothevenus** [comment]
I've resolved that error using this code.

  useEffect(() => {
    const observer = new ResizeObserver((entries) => {
      // Handle resize
    });
    const element = document.body;
    if (element) {
      console.log(element);
      observer.observe(element);
    }

    return () => {
      if (element) {
        observer.disconnect();
      } // Cleanup on unmount
    };
  }, []);

**Comment by vincent157664** [comment]
Thanks. Your code works.
