### ISSUE TITLE
Doesn't work on percentage-sized svg elements

### ISSUE THREAD

**Issue by NicolasNarvaez** [juggle/resize-observer#48]
On an svg with percentage width it wont trigger after normal resize by the resize of the surrounding elements. I didnt test if it works on other kinds of css width or height definition.

I imagine the svg elements are taken into account on the api but im not sure if im missing something.

**Comment by TremayneChrist** [comment]
Hey @NicolasNarvaes can you confirm if it works, using Chrome's native ResizeObserver?

SVGs work a bit differently, compared to other elements. Maybe you could provide a sample to look at?

**Comment by TremayneChrist** [comment]
Hi @NicolasNarvaez is this still a problem for you?

**Comment by TremayneChrist** [comment]
Closing this, but feel free to open again if you're still having problems.
