### ISSUE TITLE
Missing lib in release 2.0.1

### ISSUE THREAD

**Issue by mvsde** [juggle/resize-observer#51]
**Describe the bug**
The latest release 2.0.1 has no lib folder with build artifacts (https://unpkg.com/@juggle/resize-observer@2.0.1/lib/ResizeObserver.js).

The previous 2.0.0 release works correctly (https://unpkg.com/@juggle/resize-observer@2.0.0/lib/ResizeObserver.js).

**To Reproduce**
1. `npm i @juggle/resize-observer`
2. `import ResizeObserver from '@juggle/resize-observer'`
3. The file `/lib/ResizeObserver.js` cannot be found.

**Expected behavior**
The release has the lib folder with build artifacts.

**Additional context**
Thank you for developing this great polyfill :)

**Comment by TremayneChrist** [comment]
Oh! Thanks @mvsde will fix this ASAP!

**Comment by TremayneChrist** [comment]
All fixed. Now need to figure out why this happened 🤔
