### ISSUE TITLE
IE9 IE10 support?

### ISSUE THREAD

**Issue by TremayneChrist** [juggle/resize-observer#64]
This is here to gather feedback on the need for this. Please comment below :point_down:

**Comment by vipcxj** [comment]
If this library support ie 9/10, I will change resize-observer-polyfill to this library.

**Comment by TremayneChrist** [comment]
Tested working when these fixes are implemented 🎉 

| Unsupported Feature | Introduced | Fix for IE9+ |
|---|---|---|
| Map | IE11 | Polyfill the map API internally, or, request that a Map polyfill is included. |
| MutationObserver | IE11 | Fallback to [MutationEvents](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events). |
| requestAnimationFrame | IE10 | Fallback to setTimeout. |

**Comment by TremayneChrist** [comment]
I may put a draft of this together, but I'm worried about bloating the bundle too much. Will have a think about some options.

**Comment by TremayneChrist** [comment]
To support IE9/10, using v3.2.0 and above, you'll need to include these additional polyfills:

| Additional Polyfill | Required for |
|---|---|
| WeakMap | IE9, IE10 |
| MutationObserver | IE9, IE10 |
| devicePixelRatio | IE9, IE10 |
| requestAnimationFrame | IE9 |

I'll move this information to the readme at some point.

**Comment by TremayneChrist** [comment]
Will also add improvements so that `devicePixelRatio` and `requestAnimationFrame` are not required.
