### ISSUE TITLE
Listen to touch events to improve mobile support

### ISSUE THREAD

**Issue by TremayneChrist** [juggle/resize-observer#7]
If a device supports touch events, these should be used to detect any changes

**Comment by TheDynamicPunk** [comment]
I would like to work on this issue. Could you please guide me as to how I should proceed further as this is my first time contributing to an OSS :)

**Comment by TremayneChrist** [comment]
Hi @TheDynamicPunk  - you can look at https://github.com/juggle/resize-observer/blob/v3/src/utils/scheduler.ts#L13. It should be a case of adding the correct event names.
