### ISSUE TITLE
Server side rendering support

### ISSUE THREAD

**Issue by MurhafSousli** [juggle/resize-observer#73]
**Describe the bug**

The package causes the build system to crash when used in server-side rendering app

**To Reproduce**

Cannot be reproduced in an online platform, but try to include the package in any server-side rendering environment

**Expected behavior**

Should support server-side rendering 

---

The error thrown by the compiler:
```
var requestAnimationFrame = window.requestAnimationFrame;
ReferenceError: window is not defined
```

**Comment by TremayneChrist** [comment]
Hey @MurhafSousli,

So removing the reference of `window` here fixes it for you? I take it the other references to `window` aren't an issue, because this part of the code isn't called until it hits the client-side.

**Comment by TremayneChrist** [comment]
Ok I've checked out your repo. I get it :)

**Comment by MurhafSousli** [comment]
Hi @TremayneChrist, no it is not a plain node, I am using to do a recalculation and update the UI for a custom scrollbar library that supports SSR. https://github.com/MurhafSousli/ngx-scrollbar

**Comment by TremayneChrist** [comment]
@MurhafSousli can you try version `2.3.0`.

**Comment by TremayneChrist** [comment]
I've tested this in some different environments and all seems ok. If you're still having problems, feel free to reopen. Thanks!

**Comment by MurhafSousli** [comment]
Seems to be working fine, thanks a lot!
