### ISSUE TITLE
ResizeObserver.min.js

### ISSUE THREAD

**Issue by tobireif** [juggle/resize-observer#76]
It would be great to have a .min.js file in every release, so that it can be used in the extremely simple way of doing nothing but `<script src="ResizeObserver.min.js"></script>`.

**Comment by tobireif** [comment]
(For now I'll try https://www.jsdelivr.com/package/npm/@juggle/resize-observer
-> https://cdn.jsdelivr.net/npm/@juggle/resize-observer@2.3.0/lib/ResizeObserver.min.js )

**Comment by TremayneChrist** [comment]
Hi @tobireif,

Thanks for your idea. This has kind of been covered in #39 and the decision was to not provide a 'dist' version. This library is built as a ponyfill, so it should never modify the global (window) object. Creating a version like this would be conflicting.

**Comment by TremayneChrist** [comment]
You can always use the library via a CDN, although you'll need to cover multiple browsers..

```html
<!-- Import in ESM compatible browsers -->
<script type="module">
  import { ResizeObserver } from 'https://cdn.pika.dev/@juggle/resize-observer/v2';
  window.ResizeObserver = ResizeObserver;
</script>

<!-- Import in older browsers, using requirejs -->
<script nomodule src="https://unpkg.com/requirejs/require.js"></script>
<script nomodule>
  require.config({
    paths: {
      '@juggle/resize-observer': 'https://cdn.pika.dev/@juggle/resize-observer/v2?'
    }
  })
  require(['@juggle/resize-observer'], function (module) {
    window.ResizeObserver = module.ResizeObserver;
  })
</script>
```

**Comment by TremayneChrist** [comment]
Actually you can always use require, by forcing the UDM bundle..

```html
<script src="https://unpkg.com/requirejs/require.js"></script>
<script>
  require.config({
    paths: {
      '@juggle/resize-observer': 'https://umd.cdn.pika.dev/@juggle/resize-observer/v2?'
    }
  })
  require(['@juggle/resize-observer'], function (module) {
    window.ResizeObserver = module.ResizeObserver;
  })
</script>
```

**Comment by tobireif** [comment]
Thanks!

Currently I'm using the lib from https://github.com/que-etc/resize-observer-polyfill (minus throttling).

**Comment by TremayneChrist** [comment]
#114 could help with this.

**Comment by TremayneChrist** [comment]
Included in v4 preview
