### ISSUE TITLE
"TypeError: Invalid calling object" in IE11

### ISSUE THREAD

**Issue by mikhalovich** [juggle/resize-observer#79]
**Describe the bug**
In IE11 I have a problem with "TypeError: Invalid calling object" in the console. In other browsers (Chrome, Firefox, Safari) everything works correctly.

```
Error in mounted hook: "TypeError: Invalid calling object"
  found in
    ---> <App> at src/App.vue
      <Root>
```

**Sample Code**
Please fork this [Debug Template](https://codesandbox.io/s/qv5jpo0xlj) and help identify the issue.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE11
 - Version 11.737.17763.0

**Additional context**
My script: 
```
    const ro = new ResizeObserver((entries, observer) => {
      for (var entry of entries) {
        this.$store.dispatch('changeScreenSize', entry.contentRect.width);
        this.$emit('embedResized');
      }
    });
    ro.observe(wrapperEl);
```

**Comment by TremayneChrist** [comment]
Hi @mikhalovich could you show more of the Vue context. A small sample would be even better!

**Comment by mikhalovich** [comment]
@TremayneChrist shure. 
Actually I use [element-resize-detector](https://github.com/wnr/element-resize-detector), but it is very big package and I found your module. It is cool and work in all browsers that I need except IE11.

So, my script now looks like this:
```
// in mounted hook
const resize = elementResizeDetectorMaker(); 
const wrapperEl = this.$el.querySelector('.embed-wrapper'); //required element
resize.listenTo(wrapperEl, () => {
   this.$store.dispatch('changeScreenSize', wrapperEl.clientWidth);
   this.$emit('embedResized');
});
```

changeScreenSize action:
```
  // set screen size name
  changeScreenSize({ state, rootState, commit }, embedWidth) {
    const { screenSize:currentScreen } = state;
    const { options } = rootState.embed;
    let screenSize = 'desktop-extra-large';

    if (!options) {
      return false;
    }

    const {
      responsive_small,
      responsive_medium,
      responsive_large,
    } = options;

    const tabletSize = responsive_medium || 768;
    const desktopSize = responsive_large || 1024;
    const mobileSize = responsive_small || 480;

    if (embedWidth <= desktopSize) {
      screenSize = 'desktop';
    }

    if (embedWidth <= tabletSize) {
      screenSize = 'tablet';
    }

    if (embedWidth <= mobileSize) {
      screenSize = 'mobile';
    }

    if (currentScreen !== screenSize) {
      commit('setScreenSize', screenSize);
    }
  },
```

**Comment by TremayneChrist** [comment]
Hi @mikhalovich could you send me a reproducible repo to look at? It's hard to see where it could be erroring from this.

**Comment by TremayneChrist** [comment]
Hi @mikhalovich, I'm having a hard time trying to pinpoint this error. Are you performing any transpilation process, or, adding any other polyfills?

**Comment by TremayneChrist** [comment]
Closing this issue, as I don't feel it's linked to this library. Feel free to reopen @mikhalovich if you want to carry on the discussion.
