### ISSUE TITLE
import question

### ISSUE THREAD

**Issue by bobOnGitHub** [juggle/resize-observer#95]
Ok , this is a general web dev question but it arises from your (standard) packaging process and I can't find an answer anywhere else and no responses on [stackoverflow ](https://stackoverflow.com/q/59948493/4779501) yet. In short, how does the browser handle being given a directory in the import statement as in 

`import { ResizeObserver } from '@juggle/resize-observer';`

Chrome sends a request for '@juggle/resize-observer' which is a directory. Do I need to use a build tool with this syntax ?

**Comment by TremayneChrist** [comment]
You need module resolution for this to load. Easiest way for modern browsers is to use a CDN or a new tool like [Snowpack](https ://github.com/pikapkg/snowpack). Other options are bundlers like webpack or parcel.

CDN example:
```js
import { Resize observer } from 'https://cdn.pika.dev/@juggle/resize-observer/^3.0.2';
```

**Comment by bobOnGitHub** [comment]
Cheers. That's what I thought. 

( gonna leave the stackoverflow question up  - maybe someone'll add a link to some doc on where it all began/was agreed etc...... )

**Comment by bobOnGitHub** [comment]
@TremayneChrist sorry to bother you again but how did you come to know about server "module resolution" ? ( I can't find anything on it / am looking for documentation/specifications )

**Comment by TremayneChrist** [comment]
So it's actually Node Module Resolution https://nodejs.org/api/modules.html#modules_all_together.

Bundler implementations are based on this.

**Comment by bobOnGitHub** [comment]
Cheers for that Tremayne.,
I had just assumed it was based on a general web spec (W3C). Using Snowpack now anyway.
thanks again.
